/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProgramFrames;

import java.awt.Graphics2D;
import java.awt.*;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author MEHMETAKAN
 */
public class NewOpeningJPanel extends javax.swing.JPanel {
   Connection myconnection;
   NewMainFrame mainFrame;
    /**
     * Creates new form NewOpeningJPanel
     */
    public NewOpeningJPanel(NewMainFrame newMainFrame) {
        mainFrame = newMainFrame; 
        initComponents();
        jPasswordField1.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                jPasswordField1.setText("");
            }
        });
        //DATABASE INIT
        String url = "jdbc:mysql://localhost:3306/fireandfire";
        String username = "sqluser";
        String password = "password";
        try {
            myconnection = DriverManager.getConnection(url,username,password);
        } catch (SQLException ex) {
            //Logger.getLogger(SignUpPanel.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
            System.out.println(" CONNECTION FAILURE");
        }
    }
    public void arranger(){
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 0, 0));
        setPreferredSize(new java.awt.Dimension(2560, 1440));
        setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("USERNAME");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 30, 270, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(10, 60, 460, 60);

        jLabel2.setText("PASSWORD");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 130, 270, 30);

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(10, 160, 460, 60);

        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(190, 240, 230, 70);

        jButton2.setText("SIGN UP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(30, 360, 160, 30);

        jButton3.setText("EXIT GAME");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(40, 440, 220, 60);

        jButton4.setText("LEADERBOARDS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(130, 540, 370, 70);

        add(jPanel1);
        jPanel1.setBounds(1190, 490, 700, 650);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\MEHMETAKAN\\Desktop\\log.png")); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(2560, 1440));
        add(jLabel4);
        jLabel4.setBounds(270, -20, 2026, 1520);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean invalidLogin = true;
        String password = jPasswordField1.getText();
        String username = jTextField1.getText();
        String sql ="SELECT *FROM userData ";
       try {
           Statement statement = myconnection.createStatement();
           ResultSet result = statement.executeQuery(sql);
           while(result.next()){ // NEED A MORE EFFICIENT MECHANISM
            if(username.equals(result.getString("Username"))&&password.equals(result.getString("Passwords"))){
               jPasswordField1.setText(null);
               jTextField1.setText(null);
               invalidLogin=false;
               //myconnection.close();
               mainFrame.moveToGameLobby();
              }   
           }
           if(invalidLogin){
               JOptionPane.showMessageDialog(null, "Invalid Login Details err code: 02","Login Error",JOptionPane.ERROR_MESSAGE);
               jPasswordField1.setText(null);
               jTextField1.setText(null);   
           }
       } catch (SQLException ex) {
           //Logger.getLogger(NewOpeningJPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Invalid Login Details","Login Error",JOptionPane.ERROR_MESSAGE);
            jPasswordField1.setText(null);
            jTextField1.setText(null);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try {
           myconnection.close();
       } catch (SQLException ex) {
           Logger.getLogger(NewOpeningJPanel.class.getName()).log(Level.SEVERE, null, ex);
       }
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        //if(jTextField1.isCursorSet())
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        mainFrame.moveToSignUpPage();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        mainFrame.moveToLeaderboardsPage();
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
